kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:REGISTRY_PORT"]
    endpoint = ["http://REGISTRY_NAME:5000"]
networking:
  apiServerAddress: "127.0.0.1"
  #apiServerPort: 33333
nodes:
- role: control-plane
  extraMounts:
  - hostPath: PWD/data/controller
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "my-label1=true"
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true,my-label2=true"
  # the first worker node gets the public port for ingress
  # as soon as we have workers, we can't have pods on the controller
  extraPortMappings:
  # ingress
  - containerPort: 80
    hostPort: 8000
  # ingress
  - containerPort: 443
    hostPort: 8443
  extraMounts:
  - hostPath: PWD/data/worker1
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "my-label3=true"
  extraMounts:
  - hostPath: PWD/data/worker2
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "my-label4=true"
  extraMounts:
  - hostPath: PWD/data/worker3
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared