kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 33333
nodes:
- role: control-plane
  # add a mount from $(pwd)/data on the host to /mnt/data on the node
  extraMounts:
  - hostPath: PWD/data/controller
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "my-label1=true"
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true,my-label2=true"
  # the first worker node gets the public port for ingress
  # as soon as we have workers, we can't have pods on the controller
  extraPortMappings:
  # ingress
  - containerPort: 80
    hostPort: 8000
  # ingress
  - containerPort: 443
    hostPort: 8443
  # port forward 9090 on the host to 9090 on this node
  - containerPort: 9090
    hostPort: 9090
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    # listenAddress: "127.0.0.1"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    # protocol: TCP
  extraMounts:
  - hostPath: PWD/data/worker1
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "my-label3=true"
  extraMounts:
  - hostPath: PWD/data/worker2
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "my-label4=true"
  extraMounts:
  - hostPath: PWD/data/worker3
    containerPath: /mnt/data
  - hostPath: PWD/data/shared
    containerPath: /mnt/shared